# Generated by Django 3.2.7 on 2021-09-10 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='filesize',
            field=models.IntegerField(default=0),
        ),
    ]
